### ISSUE TITLE
using with SSR / NextJS. Warning: Did not expect server HTML to contain a <img> in <div>.

### ISSUE THREAD

**Issue by agustif** [luukdv/hamburger-react#30]
Warning: Did not expect server HTML to contain a <\img> in <\div>.
```
    at div
    at div
    at Burger (webpack-internal:///../../node_modules/hamburger-react/dist-esm/Burger.js:8:3)
    at Tilt
    at li
    at Box (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:49:26)
    at Object.attach.useProps (webpack-internal:///../../node_modules/bumbag/es/TopNav/TopNavItem.js:168:25)
    at TopNav.Item (webpack-internal:///../../node_modules/bumbag/es/utils/createComponent.js:40:104)
    at ul
    at Box (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:49:26)
    at Object.attach.useProps (webpack-internal:///../../node_modules/bumbag/es/TopNav/TopNavSection.js:138:19)
    at TopNav.Section (webpack-internal:///../../node_modules/bumbag/es/utils/createComponent.js:40:104)
    at div
    at Box (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:49:26)
    at Object.attach.useProps (webpack-internal:///../../node_modules/bumbag/es/TopNav/TopNav.js:150:19)
    at TopNav (webpack-internal:///../../node_modules/bumbag/es/utils/createComponent.js:40:104)
    at MobileMenu (webpack-internal:///./src/components/Header.tsx:106:62)
    at Header (webpack-internal:///./src/components/Header.tsx:211:86)
    at div
    at Box (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:49:26)
    at Object.attach.useProps (webpack-internal:///../../node_modules/bumbag/es/Disclosure/DisclosureContent.js:130:32)
    at Disclosure.Content (webpack-internal:///../../node_modules/bumbag/es/utils/createComponent.js:40:104)
    at div
    at Box (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:49:26)
    at Object.attach.useProps (webpack-internal:///../../node_modules/bumbag/es/Page/PageWithHeader.js:192:19)
    at PageWithHeader (webpack-internal:///../../node_modules/bumbag/es/utils/createComponent.js:40:104)
    at Layout (webpack-internal:///./src/components/Layout.tsx:24:23)
    at MyApp
    at CartProvider (webpack-internal:///../../node_modules/use-shopping-cart/dist/index.es.js:583:3)
    at Cart (webpack-internal:///./src/components/Cart.tsx:21:23)
    at div
    at Box (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:49:26)
    at Object.attach.displayName (webpack-internal:///../../node_modules/bumbag/es/Box/Box.js:149:18)
    at Box (webpack-internal:///../../node_modules/bumbag/es/utils/createComponent.js:40:104)
    at PageProvider (webpack-internal:///../../node_modules/bumbag/es/Page/PageContext.js:177:24)
    at ToastProvider (webpack-internal:///../../node_modules/bumbag/es/Toast/ToastContext.js:78:24)
    at SystemProvider (webpack-internal:///../../node_modules/reakit-system/es/SystemProvider.js:31:23)
    at unstable_IdProvider (webpack-internal:///../../node_modules/reakit/es/Id/IdProvider.js:19:23)
    at Provider (webpack-internal:///../../node_modules/reakit/es/Provider.js:13:21)
    at div
    at ColorModeProvider (webpack-internal:///../../node_modules/bumbag/es/ColorMode/ColorModeContext.js:40:24)
    at ThemeProvider
    at Provider (webpack-internal:///../../node_modules/bumbag/es/Provider/Provider.js:285:24)
    at App (webpack-internal:///./src/pages/_app.tsx:49:24)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:149:5)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:637:24)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:768:24)
```

Header.tsx

```
import React, { useState } from 'react'
import { Button, Drawer, TopNav, Box, useBreakpoint } from 'bumbag'
import Hamburger from 'hamburger-react'
import Link from 'next/link'
import { useWindowSize } from '@hooks/useWindowSize'
import Logo from '@components/Logo'
import CartWidget from '@components/CartWidget'
import { CartProvider } from '@components/CartProvider'
// import UserWidget from '@components/UserWidget'
// import SearchWidget from '@components/SearchWidget'
const Menu = (): JSX.Element => {
  return (
    <TopNav>
      <TopNav.Section>
        <Link href="/">
          <TopNav.Item style={{ marginLeft: 10 }} width="185px" fontWeight="semibold">
            <Logo />
          </TopNav.Item>
        </Link>
      </TopNav.Section>
      {/* <TopNav.Section width="100%">
        <TopNav.Item>
          <SearchWidget />
        </TopNav.Item>
      </TopNav.Section> */}
      <TopNav.Section gap="20px" marginRight="major-2">
        {/* <UserWidget /> */}
        <CartProvider>
          <CartWidget />
        </CartProvider>
      </TopNav.Section>
    </TopNav>
  )
}
const HamburgerMenu = () => {

  return(
    <>

  </>
  )
}
const MobileMenu = (): JSX.Element => {
  const drawer = Drawer.useState({ animated: true, modal: true })
  // const [isOpen, setOpen] = useState(false)
  const size = useWindowSize()
  const isWideAndUnder = useBreakpoint('max-tablet')

  return (
    <TopNav>
      <TopNav.Section>
        <TopNav.Item marginLeft="minor-2">
        <Hamburger label="Mostrar menu"  onToggle={drawer.toggle}/>

        </TopNav.Item>
      </TopNav.Section>
      <Box alignY="center" alignX="center" maxWidth="160px">
        <Logo />
      </Box>
      <TopNav.Section gap="4px" marginRight="0px" marginLeft="minor-1">
        {/* <UserWidget /> */}
        <React.Fragment>
  <Drawer
    {...drawer}
    fade
    slide
    width={isWideAndUnder ? '100%' : 400}
    style={{ overflowY: 'auto', marginTop: 79 }}
    maxWidth="420px"
    maxHeight={size.height - 80}
    >
    <a href="/">Inicio</a>
  </Drawer>
  </React.Fragment>
        <CartProvider>
          <CartWidget />
        </CartProvider>
      </TopNav.Section>
    </TopNav>
  )
}
export default function Header(): JSX.Element {
  const isTabletAndUnder = useBreakpoint('max-tablet')

  return isTabletAndUnder ? <MobileMenu /> : <Menu />
}
```

Not sure what's going on, any ideas are much appreciated, thanks for the awesome lib

**Comment by luukdv** [comment]
This error doesn't originate from `hamburger-react`, since there is no `<img>` element and no evaluation that differs based on context (SSR vs browser).

Not all relevant code is provided so it's hard to debug, but this error is based on a mismatch in the HTML that's rendered on the server vs the hydrated HTML. You could search for logic that is based on browser-specific API's that aren't available in Node. For example, rendering something based on a `window` property, `localStorage`, etc.

Let me know if you have any questions.
